### ISSUE TITLE
The framework doesn't cancel the click event

### ISSUE THREAD

**Issue by JohnnyPixelz** [stefvanschie/IF#12]
I might be stupid for saying this but as I added the framework as a dependency and made a gui object, set it up and showed it to the player, I can grab the things from inside etc (the usual nonworking-gui stuff). I wandered around your code and I cannot find any parts cancelling the event. Isn't the gui supposed to have clickable items which are unobtainable from the player?

**Comment by stefvanschie** [comment]
The behavior you described is intentional. While most guis are solely used for display purposes, this doesn't have to necessarily be the case. To ensure that both 'static' and 'non-static' guis can be created, I've decided to not automatically cancel the movement of the item. However, you can still do so yourself, by making use of the provided methods, such as Gui#setOnGlobalClick, Gui#setOnTopClick, Gui#setOnBottomClick, Pane#setOnClick and inside the GuiItem constructor depending on your use case. When working with XML you can reference a method using the optional attributes, gui::onGlobalClick, gui::onTopClick, gui::onBottomClick, pane::onClick, item::onClick, to achieve this as well.

**Comment by KotlinIsCool** [comment]
As Stef already said: this is intended behavior. You can simply add this to cancel all click events
```java
gui.setOnGlobalClick(event -> event.setCancelled(true));
```

**Comment by JohnnyPixelz** [comment]
Oh that's even better. Thanks for the support.
