### ISSUE TITLE
populateWithItemStack in PaginatedPane causes out of bounds exception

### ISSUE THREAD

**Issue by stefvanschie** [stefvanschie/IF#15]
The `populateWithItemStacks` method inside `PaginatedPane` can cause out of bounds exceptions.

Any PR for this should be pushed to branch 0.5.4.

**Comment by tth05** [comment]
Any info on the line where the IndexOutOfBoundsException happens? 
The only line I see it possibly happening is this `page.addItem(new GuiItem(items.get(index)), x, y);` but there is check a few lines before that one to make sure that it doesn't happen there.

I also spotted an error in this line `int pagesNeeded = items.size() / itemsPerPage + 1;`. It should use floating point division and Math.ceil, otherwise one more page than need will be created if `items.size() % itemsPerPage == 0`. Also the +1 would need to be removed.

**Comment by stefvanschie** [comment]
I'll do some more testing and try to get some more information. The error you showed also needs to be changed like you said. And I think that it'd be useful to replace StaticPane with OutlinePane, that way we don't have to do calculations for the x and y coordinates.

**Comment by stefvanschie** [comment]
This issue has been fixed in version 0.5.4, feel free to re-open this issue if this is not the case.
