### ISSUE TITLE
Items return to the inventory once a player closes it?

### ISSUE THREAD

**Issue by DavidTheExplorer** [stefvanschie/IF#160]
Hello, the only issue I have with your amazing library is that eventually I can't use it.
[Here ]( https://prnt.sc/1ykl4g1)is a simple command that demonstrates the problem(it uses ACF).
When a player runs the test command: the GUI opens and the player can take items, but when they run it again - all the items are still there.
This creates a problem as I want to create **endless** personal item containers.

**Comment by stefvanschie** [comment]
This is intended behavior, items moved by players will not change the underlying gui. So after updating the gui (or showing it again), the gui will be shown as it was before. Only changes made to the gui programmatically change the gui permanently.

**Comment by DavidTheExplorer** [comment]
> This is intended behavior, items moved by players will not change the underlying gui. So after updating the gui (or showing it again), the gui will be shown as it was before. Only changes made to the gui programmatically change the gui permanently.

Oh my god... then what am I supposed to do?

**Comment by stefvanschie** [comment]
You will need to track which items the player adds/removes to the gui. Then the next time the gui is opened by that player, you only show the items that are still in their personal inventory.

**Comment by DavidTheExplorer** [comment]
> You will need to track which items the player adds/removes to the gui. Then the next time the gui is opened by that player, you only show the items that are still in their personal inventory.

Can you please consider making making this possible? My plugin and possibly many big ones that entirely rely on your framework are in a very problematic state.
Thank you.

**Comment by stefvanschie** [comment]
Updating the gui in such a way that it is consistent with the players' changes is not something IF can do. There are several situations in which this would result in an odd or invalid state. Consider for example the case where a player places an item in the gui at a position where there is no pane: IF cannot add an item there, since items must be in panes. Then you might also run into a situation where there is a pane in that position, but that pane cannot store items (such as a paginated pane or masonry pane). Even if there is a proper pane, such as outline pane or pattern pane, the item at that position may still be invalid. For the outline pane the item may be at an invalid position because there are now gaps that are not supposed to be there; a gap property may be violated by leaving too few gaps between items; a pane may be repeating and the item is not part of the repetition; the mask may have set this position to be disabled. As for the pattern pane: the pane might not have the item that is being placed attached to a pattern; or if this pattern does exist, it may not be the pattern that is specified at that position. If there are multiple overlapping panes, then it is unclear to which pane the item should be added - if two overlapping panes have the same priority, there is no guarantee that their rendering order is deterministic, hence there's no way to add the item in such a way that it always shows on top.
As for removing items, this is slightly less problematic, but even removed items might leave an outline pane or pattern pane in an invalid state in similar ways as described above.

For these reasons, this is sadly not something that can be added to IF. If you know how your gui looks however - which is likely the case if you're making a gui - this becomes much easier, since you only have to consider your gui. Added and removed items can be handled in a way that works best for you.

As for deleting pages from a `PaginatedPane`, I'll add a `deletePage(int)` method so that this can be done.

**Comment by DavidTheExplorer** [comment]
Hello, any progressions on the deletion of pages? I really apologize but pretty much my entire plugin's future depends on that lol

**Comment by stefvanschie** [comment]
Sorry for the delay, I'm now working on this.

**Comment by stefvanschie** [comment]
Thank you, this will be added in 0.10.5.
