### ISSUE TITLE
Working with playerheads

### ISSUE THREAD

**Issue by ProSavage** [stefvanschie/IF#27]
Hello,

Player heads are causing an issue with IF, whenever I set the playerhead's owner, when showing the GUI, it changes the item as it has to show the player.
Then the system in IF for checking if the item stack is equal no longer works.
Since the head is changed. What can we do about tracking this somehow and making it recognize, as the head will no longer use its assigned code for cancelling event etc.

Thanks,
ProSavage

**Comment by stefvanschie** [comment]
Could you show the code that causes this issue and specify which Minecraft version you're testing this one?

**Comment by Plajer** [comment]
Possibly related to #26, check my fork where I removed equality check in order to fix that.

**Comment by ProSavage** [comment]
I simply run skull#setOwner() to create the item.

**Comment by ProSavage** [comment]
@Plajer I will check it out soon.

**Comment by stefvanschie** [comment]
IF just does a normal `ItemStack#equals` comparison on the item that was clicked and the item in the inventory. If that check leads to incorrect results, then that's probably a Bukkit/Spigot/Paper issue, since IF doesn't change that check in anyway. In that case, you'd be better off making a bug report on there.

Regardless, pull request #29 changes how item clicking is handled internally, since the previous system didn't quite work like it should. I could be mistaken, but I think this would solve your issue (as well as #26).

I'll leave this open for now and hopefully #29 fixes the issue.

**Comment by Plajer** [comment]
Thanks for info, will check this out once I'm home and tell if issue is fixed.

**Comment by stefvanschie** [comment]
0.5.9 is now out, that should hopefully fix this and #26.
