### ISSUE TITLE
Discussion: use of Bukkit's API wrapper instead of MiniNBT

### ISSUE THREAD

**Issue by Trigary** [stefvanschie/IF#48]
Since Bukkit has its own "NBT API", we should consider using it instead of a third-party library. This Bukkit one is called `PersistentDataContainer` or `org.bukkit.persistence`. Using it requires a `Plugin` instance for creating a `NamespacedKey`, but that should be no issue: `Gui` instances already keep a reference to the plugin that created them. This feature does not have any of the issues described in #45.

I would be more than happy to implement and PR this, I am just asking for input regarding it. This is a place for discussion.

**Comment by stefvanschie** [comment]
The reason I chose a third party library is because in the past some level of 1.12 support has been added; 1.12.2 doesn't have the mentioned `PersistentDataContainer`, which is why we are using MiniNBT currently. If I remember correctly, `PersistentDataContainer` is 1.14 and up, so we would have to drop both the partially supported 1.12 and 1.13. I'm personally fine with that, the question is more if others are fine with that also or if 1.12/1.13 usage is so prevalent that we should keep it supported for longer.

**Comment by A248** [comment]
Please don't do this. This would ruin plugins depending on IF which provide compatibility with multiple versions.

**Comment by Trigary** [comment]
They can choose not to use the newer versions of IF. Plugins supporting outdated, unsupported server versions are contributing to the issue and should be unsupported. At least that's what I believe, but luckily for you, stefvanschie might not be as cruel as me :)

**Comment by A248** [comment]
Multiple plugins depend on IF for clean and simple cross-version GUIs. There are plenty of good reasons to run older server versions, but that's beside the point. The fact of the matter is that this library would lose dependents if this happened. It's up to IF to maintain unified development.

**Comment by stefvanschie** [comment]
I've gone through the dependents and it seems like the majority of plugins are targeting 1.14 or higher and interest in dropping support for 1.12 and 1.13 has also been shown here. Given this, I think dropping these two versions is the best way to proceed; users who wish to continue to support 1.12/1.13 can do so by staying on the current version (0.5.19) or fork the framework and maintain this compatibility themselves.

**Comment by stefvanschie** [comment]
Addressed in #56
