### ISSUE TITLE
A dumb issue incoming...

### ISSUE THREAD

**Issue by officialrarlab** [stefvanschie/IF#49]
Yeah, not the best title...

Well, I've been having some issues looping through a Set and adding items into a static pane, my math is probably all wrong but it works very well when I enter the number itself and not by my math stuff, although I've debugged and my math doesn't seem to be wrong since it prints out the correct numbers.

Screenshot of the current issue: https://gyazo.com/ee658c4b25df45e4646d5c10b8fd50dc
My code for the explanation above is: https://sourceb.in/6e9cb16ecd 
**( The github code selector didn't want to work )**

Any assistance would be lovely at this point, thanks in advance.
~ Sincerely, RarLab.

**Comment by stefvanschie** [comment]
When the loop is at the last slot in the row (x = 8), it first computes the x value, which is 8 and then increments to 9 immediately after. Then the y value is checked: `9 != 0` becomes `true` and `9 / 9 != 0` becomes `true`, making the if statement `true`. Because of that the y value becomes `9 / 9 = 1`, so your item is placed at (8,1) which is the slot in the last column on the second row. You need to keep your x value to the actual value throughout the computation of the y value and only after that increment it, not during the computation of both values.
