### ISSUE TITLE
Raw index to coordinates

### ISSUE THREAD

**Issue by Nuckerr** [stefvanschie/IF#525]
I want to use the Slot#fromIndex function, however my index refers to the whole pane. Is there a function to just calculate slot from an index, using the whole inventory, rather than relative to a pane

**Comment by DavidTheExplorer** [comment]
Currently there is no such way. If I understand you right, if you have a pane whose top-left corner is **3, 3** - You want the _fromIndex_ method to return **4, 5** if **1, 2** is passed to it?

**Comment by Nuckerr** [comment]
Isn't that what already happens? I'm suggesting a new method, that wont be relative to the pane, so if 5,1 is passed, then it will be 5, 1, even if the gui starts at 3,3. If that is not inside the pane, then it will not be added, similar to how the coordinates slot works, but with indexes.

**Comment by stefvanschie** [comment]
I don't think this will be added. The intent of panes is that they are independent pieces of a gui, allowing you to reuse them and place them wherever you want. Absolute indexes go against this, since now items do not correlate to the position of the pane and might even be invisible depending on the position of the pane. This is not the intention of a pane.
