### ISSUE TITLE
Allow IF to be put in libraries block

### ISSUE THREAD

**Issue by supercoolspy** [stefvanschie/IF#590]
Right now IF requires shading but it is not necessarily needed any more because of the library blocks in spigot at the loaders in paper

**Comment by stefvanschie** [comment]
The classloader that gets used is different when you use the libraries section compared to shading the code. Specifically, this means that calls to `JavaPlugin.getProvidingPlugin(Class)` don't work. See also [SPIGOT-7012](https://hub.spigotmc.org/jira/browse/SPIGOT-7012). This is considered a non-issue by Spigot. If you always supply the plugin yourself when needed, e.g. by using `ChestGui(int, String, Plugin)` rather than `ChestGui(int, String)` this is not an issue, so you are safe to use the libraries block.
