### ISSUE TITLE
InventoryDragEvent is not handled/cancelled

### ISSUE THREAD

**Issue by Phoenix616** [stefvanschie/IF#60]
The listener currently does not seem to handle or cancel the InventoryDragEvent. This could lead to cases where a player could insert (and loose) items into the GUI or even extracting them as dragging of an item (even for a single pixel!) does not call a click event anymore but a drag event. The best solution imo. would be to just cancel it and handle it as if it was clicked if only one item was dragged. (This would allow accidental drags that are meant to be clicks but resulted in slight mouse movement to still be counted as clicks)

**Comment by stefvanschie** [comment]
I'm not certain if I completely understand the scenario you're describing in which this could cause issues.

From my testing, dragging indeed does not seem to fire an `InventoryClickEvent`, however for a player to be able to drag, they must first have the item they are going to drag on their cursor. Moving an item from the inventory into the player's cursor seems to be only possible by clicking on the item, which does fire an `InventoryClickEvent`. Assuming you don't want items to be moved in the inventory, cancelling the `InventoryClickEvent` via either the gui, pane or item itself ensures this item will never get on the player's cursor in turn also making it impossible for them to drag this item. Of course if clicking on an item is allowed and not cancelled then this dragging is possible, yet if the `InventoryDragEvent` would then be handled as an `InventoryClickEvent` this would also not be cancelled (since the initial event fired from picking up the item from the inventory into the cursor was also not cancelled and these events would then be handled the same).

**Comment by Phoenix616** [comment]
Take two different situations:

- The player has a stack of items on the cursor. Now they drag it over free spots on the GUI. These items would then be inserted into the GUI and be effectively lost. Simply cancelling the drag event there would've stopped the player from loosing items.
- The player has a couple of the same item stacks on the cursor which are also displayed in the GUI. He can now extract items from the GUI by dragging over them with the stack slightly. (Hard to manage but seems to be possible)
- The player has nothing in the hand. He drags over an item in the GUI (not over slots) and manages to extract it to the cursor. (A lot harder than the other one but still possible, managed to do this myself before)

All of these fire the drag event and are prevented by simply cancelling this.

Forwarding the dragging as a normal click is just a convenience method I use in order to ensure that even if the player clicks and moves the mouse accidentally (which still fires a drag and not a click) will result in a click so that the GUI will not randomly not work for the player.

**Comment by stefvanschie** [comment]
This has been addressed in the latest commit, thank you.
