### ISSUE TITLE
Players receiving items while their inventory is also used as a GUI

### ISSUE THREAD

**Issue by Trigary** [stefvanschie/IF#61]
What happens while players receive items while their inventory (the player inventory) is also used as a GUI?

As far as I know, there are two main ways in which players can receive items:
 - `PlayerPickupItemEvent`: this event could simply be cancelled while such an IF GUI is opened
 - `Inventory#addItem` or equivalent methods: we could attempt to detect foreign items in the GUI when it is updated/closed and just drop them on the ground

Still an issue: `Inventory#removeItem`, which might be used for eg. item-based economies.

The best solution would be to publish the GUI to the player using packets, in which case the Bukkit API method calls from other plugins, etc would still act upon the real player GUI. But such a system is complicated and probably beyond the scope of this project, especially due to maintenance costs.

I personally believe the best course of action, if it's not already done, is to cancel the `PlayerPickupItemEvent` if such a IF GUI is open, and leave this issue at that. The other solutions are too complicated and the problems they solve are probably orders of magnitude rarer.

**Comment by stefvanschie** [comment]
I agree that the proposed packet-based option is beyond the scope of this project.

IF currently does not handle the `PlayerPickupItemEvent` like you mentioned, so that needs addressing. I think that adding the items to the internal cached inventory however would work better than only cancelling the event and keeping the items on the ground. This way players can still get items in their inventory and those can't be picked up by other people, without messing up the bottom inventory for the current GUI.

**Comment by stefvanschie** [comment]
This issue has been addressed in the latest commit, thank you.
