### ISSUE TITLE
when pressing the "swap item in offhand key" the item gets duped into the offhand

### ISSUE THREAD

**Issue by superbiebel** [stefvanschie/IF#95]
Even when u set inventoryclickevent#setCancelled(true) the item gets duped to the offhand. (i only tested this with the chestgui)

possible fix:
listen to the PlayerSwapHandItemsEvent and then distribute that event like the inventoryclickevent to the gui and the items of the gui.

**Comment by stefvanschie** [comment]
Thank you, this appears to be a Spigot bug. I've opened a Spigot issue report, which can be found here: https://hub.spigotmc.org/jira/browse/SPIGOT-6291.

**Comment by stefvanschie** [comment]
As also mentioned in the referenced Spigot issue, this is caused by a client issue not updating the off hand even if a packet is being sent overriding the off hand item when it has an inventory open. As a work-around for this, IF will now reset the off hand item for the client when a gui is closed/updated, which should slightly alleviate this issue. Unfortunately, it seems to not be possible to completely resolve this issue with this issue in the client without potentially creating unwanted side-effects server-side, so it seems like this will have to do for now.
